import { motion } from "framer-motion";
import { useAsconStore } from "@/store/useAsconStore";
import { Play, Pause, SkipBack, SkipForward, FastForward, Settings } from "lucide-react";
import { InteractiveStateGrid } from "@/components/studio/InteractiveStateGrid";
import { InputConfigurationPanel } from "@/components/studio/modules/InputConfigurationPanel";
import { PermutationExplorer } from "@/components/studio/modules/PermutationExplorer";
import { AssociatedDataFlow } from "@/components/studio/modules/AssociatedDataFlow";
import { PlaintextProcessingFlow } from "@/components/studio/modules/PlaintextProcessingFlow";
import { FinalizationAndTag } from "@/components/studio/modules/FinalizationAndTag";

export function GuidedLaboratory() {
  const { currentStepIndex, steps, playbackState, setPlaybackState, nextStep, prevStep, session } = useAsconStore();
  const progress = ((currentStepIndex) / (steps.length - 1)) * 100;

  const currentStage = steps[currentStepIndex];

  const renderActiveVisual = () => {
    switch (currentStage) {
      case "INTRODUCTION":
        return (
          <div className="text-center p-8 flex flex-col items-center max-w-2xl">
            <div className="w-24 h-24 bg-blue-500/20 rounded-full flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(59,130,246,0.3)] border border-blue-500/30">
               <svg className="w-12 h-12 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 11c0 3.517-1.009 6.799-2.753 9.571m-3.44-2.04l.054-.09A13.916 13.916 0 008 11a4 4 0 118 0c0 1.017-.07 2.019-.203 3m-2.118 6.844A21.88 21.88 0 0015.171 17m3.839 1.132c.645-2.266.99-4.659.99-7.132A8 8 0 008 4.07M3 15.364c.64-1.319 1-2.8 1-4.364 0-1.457.39-2.823 1.07-4" /></svg>
            </div>
            <h2 className="text-3xl font-bold text-white mb-4 leading-tight">You are about to encrypt data generated by an IoT device.</h2>
            <p className="text-zinc-400 text-lg leading-relaxed mb-8">
              This is a fully deterministic, interactive laboratory. It will guide you through the complete ASCON cryptographic process, taking a real <b>ESP32 temperature reading</b> from zero knowledge to a authenticated ciphertext.
            </p>
            <button onClick={nextStep} className="bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 px-8 rounded-full shadow-[0_0_20px_rgba(37,99,235,0.4)] transition-all">
              START ENCRYPTION JOURNEY
            </button>
          </div>
        );
      case "SENSOR_DATA":
        return (
          <div className="text-center p-8 flex flex-col items-center">
            <h3 className="text-zinc-500 uppercase tracking-widest font-bold text-sm mb-2">Original Information</h3>
            <h2 className="text-[5rem] font-black text-white mb-6 drop-shadow-[0_0_20px_rgba(255,255,255,0.2)]">
              {session.sensorReading}
            </h2>
            <div className="bg-white/5 border border-white/10 rounded-2xl p-6 w-72 text-left mb-6">
              <p className="text-zinc-400 text-sm mb-2"><span className="text-zinc-600 w-20 inline-block font-mono">Device:</span> <span className="text-white font-medium">{session.deviceId}</span></p>
              <p className="text-zinc-400 text-sm mb-2"><span className="text-zinc-600 w-20 inline-block font-mono">Sensor:</span> <span className="text-white font-medium">Temperature</span></p>
              <p className="text-zinc-400 text-sm mb-2"><span className="text-zinc-600 w-20 inline-block font-mono">Status:</span> <span className="text-green-400 font-medium">Received securely</span></p>
            </div>
            {session.sessionId.startsWith("DEMO") && (
              <p className="text-yellow-500/80 bg-yellow-500/10 px-4 py-2 rounded-lg text-xs font-mono border border-yellow-500/20">
                Demo Mode: this value is deterministic and is used to make the demonstration reproducible.
              </p>
            )}
          </div>
        );
      case "PREPARE_DATA":
      case "CRYPTO_PARAMS":
        return <InputConfigurationPanel />; 
      case "INITIAL_STATE":
      case "INITIALIZATION":
      case "PERMUTATION":
      case "SUBSTITUTION":
      case "DIFFUSION":
        return <PermutationExplorer />; 
      case "PLAINTEXT_PROCESSING":
        return <PlaintextProcessingFlow />;
      case "FINALIZATION":
      case "AUTH_TAG":
      case "FINAL_RESULT":
        return <FinalizationAndTag />;
      default:
        return <div className="w-full h-full flex items-center justify-center"><InteractiveStateGrid /></div>;
    }
  };

  return (
    <div className="flex flex-col h-full relative">
      <div className="flex-1 min-h-0 relative flex items-center justify-center p-2">
        {renderActiveVisual()}
      </div>

      <div className="mt-auto pt-6 border-t border-white/10 flex flex-col gap-4">
        <div className="flex items-center gap-3 w-full">
           <span className="text-xs text-zinc-500 w-12 text-right font-mono">Step {currentStepIndex}</span>
           <div className="flex-1 h-2 bg-white/5 rounded-full overflow-hidden relative">
             <motion.div 
               className="absolute top-0 left-0 h-full bg-blue-500" 
               initial={{ width: 0 }}
               animate={{ width: `${progress}%` }}
               transition={{ duration: 0.3 }}
             />
           </div>
           <span className="text-xs text-zinc-500 w-16 text-left font-mono">of {steps.length - 1}</span>
        </div>
        
        <div className="flex items-center justify-between">
           <div className="flex items-center gap-2">
             <button className="p-2 bg-white/5 hover:bg-white/10 rounded-full text-zinc-400 hover:text-white transition-colors">
               <Settings className="w-4 h-4" />
             </button>
           </div>
           
           <div className="flex items-center gap-4 bg-[#09090b] px-4 py-2 rounded-full border border-white/10 shadow-xl">
             <button onClick={prevStep} disabled={currentStepIndex === 0} className="p-2 text-zinc-400 hover:text-blue-400 transition-colors disabled:opacity-20 disabled:hover:text-zinc-400">
               <SkipBack className="w-5 h-5 fill-current" />
             </button>
             
             <button 
               onClick={() => setPlaybackState(playbackState === 'playing' ? 'paused' : 'playing')}
               className="p-3 bg-blue-600 hover:bg-blue-500 text-white rounded-full transition-all shadow-[0_0_15px_rgba(37,99,235,0.4)]"
             >
               {playbackState === 'playing' ? <Pause className="w-6 h-6 fill-current" /> : <Play className="w-6 h-6 fill-current ml-1" />}
             </button>
             
             <button onClick={nextStep} disabled={currentStepIndex === steps.length - 1} className="p-2 text-zinc-400 hover:text-blue-400 transition-colors disabled:opacity-20 disabled:hover:text-zinc-400">
               <SkipForward className="w-5 h-5 fill-current" />
             </button>
           </div>

           <div className="flex items-center gap-2">
             <button className="flex items-center gap-1 px-3 py-1.5 bg-white/5 hover:bg-white/10 rounded-full text-zinc-400 hover:text-white transition-colors text-xs font-semibold">
               <FastForward className="w-4 h-4" /> 1.0x
             </button>
           </div>
        </div>
      </div>
    </div>
  );
}
